require 'fileutils'

module Dropsite
  # Main site builder class. Some inspiration here from Jekyll (github.com/mojombo/jekyll).
  class Site
    attr_reader :site_tree, :public_dir, :exclude, :disabled_plugins, :site_files_dir

    def initialize(config)
      if config.is_a? String
        @public_dir = config
        @exclude, @disabled_plugins = [], []
        @quiet = false
      elsif config.is_a? OpenStruct
        @config = config.clone
        @public_dir = config.public_dir
        @exclude = config.exclude || []
        @disabled_plugins = config.disabled_plugins || []
        @quiet = config.quiet || false
      elsif config.is_a? Hash
        @config = config.clone
        @public_dir = config[:public_dir]
        @exclude = config[:exclude] || []
        @disabled_plugins = config[:disabled_plugins] || []
        @quiet = config[:quiet] || false
      end

      @site_tree = nil
      @site_files_dir = File.join(@public_dir, 'dropsite')
    end

    def process
      clean
      read
      render
      write
    end

    # Cleans up files previously generated by Dropsite (or at least ones)
    # that look like they are. By default this will be an index.html
    # file and dropsite directory in the Public directory root.
    def clean
      if File.exist?(@site_files_dir)
        notice "Deleting existing site files dir at #{@site_files_dir}"
        FileUtils.rm_rf(@site_files_dir)
      end

      index_file = File.join(@public_dir, 'index.html')
      if File.exist?(index_file)
        notice "Deleting existing top-level index at #{index_file}"
        File.delete(index_file)
      end
    end

    def read
      @site_tree = read_directory
    end

    def render
      site_tree.render
    end

    def write
      notice "Creating site files dir at #{site_files_dir}"
      Dir.mkdir(site_files_dir)
      site_tree.write

      Dir.mkdir(assets_dir)
      DirRenderer.renderers.each do |r|
        if File.exist? r.assets_dir
          FileUtils.cp_r(r.assets_dir, File.join(assets_dir, underscorize(r.class.to_s)))
        end
      end
    end

    def assets_dir
      File.join(@site_files_dir, 'dropsite-assets')
    end

    # User message themes loosely based on those from github.com/mxcl/homebrew

    # Output a normal user message
    def notice(msg, strong=false)
      return if @quiet
      puts "#{Tty.blue}==>#{strong ? Tty.bold_white : Tty.reset + Tty.white} #{msg}#{Tty.reset}"
    end

    # Output a warning message
    def warning(msg)
      return if @quiet
      puts "#{Tty.red}Warning#{Tty.reset}: #{msg}"
    end

    # Output an error message
    def error(msg, err=nil)
      return if @quiet
      puts "#{Tty.red}Error#{Tty.reset}: #{msg}#{', details follow...' if err}"
      puts err.to_s if err
    end

    protected

    def read_directory(dir='')
      base = File.join(@public_dir, dir)
      entries = filter_entries(Dir.entries(base))

      dir_entries = []

      entries.each do |f|
        f_abs = File.join(base, f)
        f_rel = File.join(dir, f).sub(/^\//, '')
        if File.directory?(f_abs)
          dir_entries << read_directory(f_rel)
        elsif !File.symlink?(f_abs)
          # Ignore a top level Icon file, used for a custom directory icon on OS X
          # TODO: find out how to do this specifically for the Icon file... there is a
          #       weird character at the end of the folder icon file name
          next if RUBY_PLATFORM =~ /darwin/ && f_rel =~ /^Icon/ && f_rel.size == 5 && dir == ''
          dir_entries << SiteFile.new(f_rel, f_abs, self)
        end
      end
      SiteDir.new(dir, dir_entries, self)
    end

    def filter_entries(entries)
      entries.reject do |e|
        ['.', '_', '#'].include?(e[0..0]) || e[-1..-1] == '~' || @exclude.include?(e)
      end
    end
  end
end

# Add a little color - based on some stuff from github.com/mxcl/homebrew
class Tty
  class << self
    def blue; bold 34; end
    def white; escape 39; end
    def bold_white; bold 39; end
    def red; underline 31; end
    def yellow; underline 33 ; end
    def reset; escape 0; end
    def em; underline 39; end

    private
    def color(n); escape "0;#{n}" end
    def bold(n); escape "1;#{n}" end
    def underline(n); escape "4;#{n}" end
    def escape(n); "\033[#{n}m" if $stdout.tty? end
  end
end
